### PR TITLE
fix(graphql): enum types get cached (#35)

### PR DESCRIPTION
**Pull request by artem-barmin**
Fix for https://github.com/calebmer/postgraphql/issues/35

Enum types get cashed using default memoize resolver. Removed schema validation error

### CODE REVIEW

**Comment by calebmer** [comment]
Thanks for the fix, and tests all pass great job! Do you mind cleaning up the lint errors?

**Comment by artembarmin** [comment]
Lint erros fixed. Do you have another requirements?

**Comment by calebmer** [comment]
Nope, thanks so much 😊 🎉

**Comment by calebmer** [comment]
Published in `1.2.2` 👍

**Pull request merged**
