### PR TITLE
feat(graphql): add relay example [don’t merge]

### PR DESCRIPTION
**Pull request by ferdinandsalis**
Only to have it out in the open. Still a lot of things missing. **Happy for any input especially about the scope of this example.** Let me know what you want to see.

### CODE REVIEW

**Comment by calebmer** [comment]
Yay! I'm going to be super excited when this gets merged 🙌

**Comment by ferdinandsalis** [comment]
@calebmer do you have any wishes regarding the scope of this example. For example should it include routing (`react-router` and `react-router-relay`). I guess to really put relay to its test it would make sense, right?

**Comment by calebmer** [comment]
Yes. I want PostGraphQL not only to be a great app, but also a great learning resource. So yeah, let's not go too far but `react-router`/`react-router-relay` seems like a good choice to further that goal.

**Comment by calebmer** [comment]
In the future I do want to also write comprehensive information on designing good PostgreSQL schemas 😊

**Comment by ferdinandsalis** [comment]
> In the future I do want to also write comprehensive information on designing good PostgreSQL schemas

@calebmer I would love to have that ☺️

**Comment by ferdinandsalis** [comment]
Closing this, since this is now on the main repo — https://github.com/calebmer/postgraphql/tree/feat/relay-example

**Pull request closed without merging**
