### PR TITLE
Cast a.attnum to int

### PR DESCRIPTION
**Pull request by rattrayalex**
Addresses https://github.com/calebmer/postgraphql/issues/12

### CODE REVIEW

**Comment by calebmer** [comment]
Per chance, what PostgreSQL version are you using?

**Comment by rattrayalex** [comment]
9.4.5

**Comment by calebmer** [comment]
Ok cool, I've been testing on 9.5 myself 😊

I definitely want to merge and release this, I just need to setup CI first, so that might take me a bit.

**Comment by calebmer** [comment]
I decided to merge and test locally so you wouldn't have to rebase my CI commit and got the following error: `operator does not exist: smallint[] @> integer[]`. I rolled back, so could you submit the PR again so it can hit CI and we can debug together?

**Comment by rattrayalex** [comment]
Huh, interesting. Yes, happy to - unsure if I'll be able to w/in 24h.

First guess is that casting the other side of the expression go int might
do the trick...

**Pull request merged**
