### PR TITLE
fix(postgres): fix processing money type

### PR DESCRIPTION
**Pull request by benjie**
Finally got around to figuring out what was wrong with the tests for me...

I'm concerned that the removal of commas might be localization dependent too, for example in continental Europe they tend to place commas where we place dots and vice versa; e.g. €1.234,56 - if this is the case for the money type then things are going to go wrong... 😜

### CODE REVIEW

**Comment by calebmer** [comment]
Do you think it would be worth using something like https://github.com/openexchangerates/accounting.js for parsing monetary formats? Because you’re right about the localization thing 😉

**Comment by benjie** [comment]
Seems overkill; could we just cast the column to float or decimal when selecting?

**Comment by benjie** [comment]
@calebmer Should we merge this as-is and revisit accounting.js at a later date? I'm just aware that currently the money type doesn't work outside the US for anyone...

**Comment by calebmer** [comment]
Yep 👍

Just waiting for CI to pass now…

**Pull request merged**
