### PR TITLE
Add docker-compose file for docker development.

### PR DESCRIPTION
**Pull request by pvdvreede**
Was wondering if this would be useful for other people to make getting started on development of postgraphql easier?

I do all my development with docker and docker-compose so wanted to add this in so that I can have a play with postgraphql and see if I can help with development.

If you are not a regular node dev this will make it easier for people to get started quickly.

### CODE REVIEW

**Comment by pvdvreede** [comment]
This seems to be failing on the linter due to styling issues unrelated to this PR.

**Comment by calebmer** [comment]
Thanks for your contribution! Sorry for taking so long to review, I’ve been swamped with work 😖

I presently think that (especially on OSX) the development with PostgreSQL workflow is one of the best available so I don’t see the need for docker.

I’m not going to close this because I don’t want to be close minded, but if at least one other person else were to validate a need for this I’d happily merge 😊

**Comment by pvdvreede** [comment]
No worries, its not too big of a deal, I can just copy this docker-compose file into the repo whenever I want to develop.

It would be good to keep the PR open to see if anyone else is for it.

**Comment by dts** [comment]
I was just rolling through here to check for a deployment docker container (found it, thanks!).  But I thought I'd add my two cents, so that @pvdvreede doesn't feel all alone 😄 . I exclusively do development in Docker, it allows me to keep my stockings straight with different node requirements as I have code spanning a half-decade of Node.  Trying to manage native bindings for node 0.10 through 6.* is impossible otherwise!!  I use volume sharing to allow for rapid code iteration - my basic environment is described here: https://medium.com/the-human-effort/getting-docker-node-and-npm-to-play-nice-a61c0c2c516a#.24iq5gdx2

**Comment by calebmer** [comment]
I’m going to close this. I really want to educate on Docker deployment with PostGraphQL, so if you want to write a documentation article on deploying PostGraphQL and Postgres in Docker containers, that would be awesome :blush:

**Pull request closed without merging**
