### PR TITLE
Authorization and authentication

### PR DESCRIPTION
**Pull request by calebmer**
This PR's goal is to add authorization and optional authentication to PostGraphQL. As of the opening of this issue I have only added authorization support using JWTs. Look at the tests, look at the readme, and look at [this](https://github.com/calebmer/postgraphql/blob/feat/auth/docs/pg-jwt-spec.md) specification and tell me if you like this authorization schema. Authentication (creating tokens) will be decided later on.

### CODE REVIEW

**Comment by hardchor** [comment]
I like the spec, but would you just parse all claims globally or, or namespace them, e.g.

```JSON
{
  "roles": {
    "sub": "postgraphql",
    "role": "user",
    "user_id": 2
  }
}
```

We've used JWTs in the past to store arbitrary data (that needed to be trusted), which would get picked up and set as a role with your solution.

**Comment by calebmer** [comment]
Only the top level role would be used to set the role. If there was a nested object it would be stringified. So `role` inside the `roles` object would not be used to set the role. Does this still cause conflicts?

If so we could have a flag in the JWT to switch it off.

**Comment by hardchor** [comment]
Ah sorry, I wasn't aware it's only the role field that gets set, everything else can get discarded if not needed. If it's just role, then chances for collisions are relatively low.

**Comment by calebmer** [comment]
@hardchor is there a way I could improve the documentation/specification to make this more clear?

**Comment by hardchor** [comment]
I just wasn't quite aware of how authorisation in Postgres works (do very little DB related these days). After reading the spec again, it does make sense!

**Comment by hardchor** [comment]
Are you going to pass the token / claims in through the GraphQL context? I'm doing the request handling myself (and just use `createGraphqlSchema ` as discussed) and would also do JWT decoding / verification.

**Comment by calebmer** [comment]
Currently, the token is used to run some queries on the PostgreSQL client and is unused by resolvers so it isn't needed in the context. I also don't want to be setting the local variables more than once so putting token serialization in the resolver isn't optimal. Take a look at `createServer.js` for the code I'm using currently to run a request.

I think what I'll probably do is make a small module (`pg-jwt` probably) which will implement the specification so you can serialize a token from anywhere.

I could also add a helper function, `executeGraphqlQuery` or `getGraphqlContext` to help setup the context.

**Comment by calebmer** [comment]
I was going to wait to also implement authentication before merging this PR, but I don't have any strong ideas at the moment. How would everyone feel if I merged and released this and work on an authentication solution in another PR?

Releasing this would not be a breaking change, servers would still work even if they never use tokens. People using PostGraphQL as a library would not be affected at all by this PR as it only changes code in the server.

**Comment by hardchor** [comment]
I'd say handle authorisation and authentication separately and get it in!

**Comment by calebmer** [comment]
Authorization support has been added in `1.2.0`! Documentation on the feature isn't very rich, I'm going to wait for authentication before writing comprehensive documentation on authorization/authentication

**Pull request merged**
