### PR TITLE
feat(docs): add to readme a link to contributing

### PR DESCRIPTION
**Pull request by valorize**
@benjie

### CODE REVIEW

**Comment by benjie** [comment]
@valorize Thanks 👍  have tweaked and will merge.

In future, I'd advise that you create a branch for each pull request - pulling from your `master` means any changes you make to your `master` before the PR is merged will be added to the PR which may not be what you intend.

Also have a look at the commit naming in contributing.md :)

**Comment by benjie** [comment]
@calebmer Just wanted to check you're okay with this change.

**Comment by valorize** [comment]
When I run the tests, should all tests pass in the moment (commit: 7f1a21b4b5e907a72f093bd72667477b7c608110)? Because two of 2 of 498 failed.

**Comment by valorize** [comment]
```
Summary of all failing tests
 FAIL  src/graphql/schema/__tests__/createMutationGqlField-test.js
  ● will add `outputFields` in payload type and skip falsies

    expect(received).toEqual(expected)
    
    Expected value to equal:
      {"args": [{"defaultValue": undefined, "description": null, "name": "arg", "type": {"_scalarConfig": {"description": "The `String` scalar type represents textual data, represented as UTF-8 character sequences. The String type is most often used by GraphQL to represent free-form human-readable text.", "name": "String", "parseLiteral": [Function parseLiteral], "parseValue": [Function String], "serialize": [Function String]}, "description": "The `String` scalar type represents textual data, represented as UTF-8 character sequences. The String type is most often used by GraphQL to represent free-form human-readable text.", "name": "String"}}], "deprecationReason": Symbol(deprecationReason), "description": Symbol(description), "isDeprecated": true, "name": "c", "resolve": [Function anonymous], "type": {"_scalarConfig": {"description": "The `String` scalar type represents textual data, represented as UTF-8 character sequences. The String type is most often used by GraphQL to represent free-form human-readable text.", "name": "String", "parseLiteral": [Function parseLiteral], "parseValue": [Function String], "serialize": [Function String]}, "description": "The `String` scalar type represents textual data, represented as UTF-8 character sequences. The String type is most often used by GraphQL to represent free-form human-readable text.", "name": "String"}}
    Received:
      {"args": [{"defaultValue": null, "description": null, "name": "arg", "type": {"_scalarConfig": {"description": "The `String` scalar type represents textual data, represented as UTF-8 character sequences. The String type is most often used by GraphQL to represent free-form human-readable text.", "name": "String", "parseLiteral": [Function parseLiteral], "parseValue": [Function String], "serialize": [Function String]}, "description": "The `String` scalar type represents textual data, represented as UTF-8 character sequences. The String type is most often used by GraphQL to represent free-form human-readable text.", "name": "String"}}], "deprecationReason": Symbol(deprecationReason), "description": Symbol(description), "isDeprecated": true, "name": "c", "resolve": [Function anonymous], "type": {"_scalarConfig": {"description": "The `String` scalar type represents textual data, represented as UTF-8 character sequences. The String type is most often used by GraphQL to represent free-form human-readable text.", "name": "String", "parseLiteral": [Function parseLiteral], "parseValue": [Function String], "serialize": [Function String]}, "description": "The `String` scalar type represents textual data, represented as UTF-8 character sequences. The String type is most often used by GraphQL to represent free-form human-readable text.", "name": "String"}}
    
    Difference:
    
    - Expected
    + Received
    
      Object {
        "args": Array [
          Object {
    -       "defaultValue": undefined,
    +       "defaultValue": null,
            "description": null,
            "name": "arg",
            "type": GraphQLScalarType {
              "_scalarConfig": Object {
                "description": "The `String` scalar type represents textual data, represented as UTF-8 character sequences. The String type is most often used by GraphQL to represent free-form human-readable text.",
                "name": "String",
                "parseLiteral": [Function parseLiteral],
                "parseValue": [Function String],
                "serialize": [Function String],
              },
              "description": "The `String` scalar type represents textual data, represented as UTF-8 character sequences. The String type is most often used by GraphQL to represent free-form human-readable text.",
              "name": "String",
            },
          },
        ],
        "deprecationReason": Symbol(deprecationReason),
        "description": Symbol(description),
        "isDeprecated": true,
        "name": "c",
        "resolve": [Function anonymous],
        "type": GraphQLScalarType {
          "_scalarConfig": Object {
            "description": "The `String` scalar type represents textual data, represented as UTF-8 character sequences. The String type is most often used by GraphQL to represent free-form human-readable text.",
            "name": "String",
            "parseLiteral": [Function parseLiteral],
            "parseValue": [Function String],
            "serialize": [Function String],
          },
          "description": "The `String` scalar type represents textual data, represented as UTF-8 character sequences. The String type is most often used by GraphQL to represent free-form human-readable text.",
          "name": "String",
        },
      }
      

 FAIL  src/postgraphql/__tests__/postgraphqlIntegrationOperations-test.js (58.01s)
  ● operation dynamic-json.graphql

    expect(value).toMatchSnapshot()
    
    Received value does not match stored snapshot 1.
    
    - Snapshot
    + Received
    
      Object {
    -   "data": Object {
    -     "a": true,
    -     "allTypes": Object {
    -       "nodes": Array [
    -         Object {
    -           "json": Object {
    -             "a": 1,
    -             "b": 2,
    -             "c": 3,
    -             "d": Object {
    -               "e": 4,
    -               "f": 5,
    -               "g": Array [
    -                 6,
    -                 7,
    -                 8,
    -                 "x",
    -                 false,
    -                 null,
    -               ],
    -             },
    -           },
    -           "jsonb": Object {
    -             "1": "a",
    -             "2": "b",
    -             "3": "c",
    -             "4": Object {
    -               "5": "d",
    -               "6": "e",
    -               "7": Array [
    -                 "f",
    -                 "g",
    -                 "h",
    -                 42,
    -                 true,
    -                 null,
    -               ],
    -             },
    -           },
    -         },
    -       ],
    -     },
    -     "b": false,
    -     "c": 42,
    -     "d": 3.1415,
    -     "e": "hello, world!",
    -     "f": Object {
    -       "a": 1,
    -       "b": 2,
    -       "c": 3,
    -     },
    -     "g": Array [
    -       1,
    -       2,
    -       3,
    -       4,
    -     ],
    -     "h": Object {
    -       "array": Array [
    -         1,
    -         2,
    -         3,
    -         4,
    -       ],
    -       "boolean": true,
    -       "float": 3.1415,
    -       "integer": 42,
    -       "object": Object {
    -         "a": 1,
    -         "b": 2,
    -         "c": 3,
    -       },
    -     },
    -     "i": Array [
    -       true,
    -       42,
    -       3.1415,
    -       Object {
    -         "a": 1,
    -         "b": 2,
    -         "c": 3,
    -       },
    -       Array [
    -         1,
    -         2,
    -         3,
    -         4,
    -       ],
    -     ],
    -     "j": Array [
    -       true,
    -       null,
    -       42,
    -       3.1415,
    -       Object {
    -         "a": 1,
    -         "b": null,
    -         "c": 3,
    -       },
    -       Array [
    -         1,
    -         2,
    -         null,
    -         3,
    -         4,
    -       ],
    -     ],
    -   },
    +   "errors": Array [
    +     [GraphQLError: Syntax Error GraphQL request (14:32) Unexpected Name "null"
    + 
    + 13:   i: jsonIdentity(json: [true, 42, 3.1415, { a: 1, b: 2, c: 3 }, [1, 2, 3, 4]])
    + 14:   j: jsonIdentity(json: [true, null, 42, 3.1415, { a: 1, b: null, c: 3 }, [1, 2, null, 3, 4]])
    +                                    ^
    + 15:   allTypes {
    + ],
    +   ],
      }
      
      at next (native)
      at process._tickCallback (internal/process/next_tick.js:103:7)
```

**Comment by benjie** [comment]
As it happens that's exactly the same reason https://github.com/calebmer/postgraphql/pull/212 is failing.

@calebmer 🚨  I think we should change the ts-node dependency from `"ts-node": "^1.6.1"` to `"ts-node": "^1.6.1 <1.7"` (or whatever the semver spec is) if we don't have time to fix whatever's broken. (It's still beyond me, I'm afraid.)

@valorize Try: `npm install ts-node@1.6.1` and try again.

**Comment by calebmer** [comment]
What this failure looks like to me is a GraphQL version less then `0.8.2` which adds support for `null` literals. My theory on why Travis is failing is I believed they recently moved to Yarn over npm, so the resolution algorithm/cache may be pulling in the wrong GraphQL version. I’m going to experiment :+1:

**Comment by calebmer** [comment]
Yeah, anyway thanks so much for this change @valorize :tada:

I can confirm that the failing tests are caused by a GraphQL-js version less then `0.8.x`. I just merged a PR which hopefully will enforce version `0.8.x` in development. We support any version of GraphQL-js in production, but the tests depend on version `0.8.x` :blush:

**Comment by valorize** [comment]
Cool with the latest npm update all tests went green.

**Pull request merged**
