### PR TITLE
feat(graphql): add relay example

### PR DESCRIPTION
**Pull request by ferdinandsalis**
Happy for any input especially about the scope of this example. Let me know what you want to see.

### CODE REVIEW

**Comment by ferdinandsalis** [comment]
I will be adding mutations next …

**Comment by ferdinandsalis** [comment]
@calebmer still here just currently entrenched in work stuff ☺️  Will continue soon.

**Comment by tim-field** [comment]
Would love to see user authentication!

**Comment by ferdinandsalis** [comment]
@tim-field would love to see that too 😁. Maybe you want to give it a try? 😊  I want to add it eventually though.

**Comment by ferdinandsalis** [comment]
@calebmer I am starting to get somewhere. Some things are still missing though. Like signing up and changing your account details, etc. Anyways it would be great if you could take a look at and point out some things that I should add, remove or improve.

**Comment by ferdinandsalis** [comment]
I will keep things you mentioned in https://github.com/calebmer/postgraphql/issues/113 in mind when I finish up this example. Please note that I am quite new to many of the concepts used and some of my assumptions might be wrong. Please doubt my assumptions 😊

**Comment by calebmer** [comment]
No problem, I definitely intend to review once its done so we can go over assumptions together :+1:

**Comment by ferdinandsalis** [comment]
I am closing this since this will be moved over to the newest version of PostGraphQL.

**Pull request closed without merging**
